### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lj222kj** [don/cordova-plugin-ble-central#143]
Hi! Are you planning to support the windows-platform? :)

**Comment by don** [comment]
Windows support is on the roadmap, but it's not high priority. Unfortunately Windows (and Windows Phone) idea of scanning and connecting is completely different from iOS and Android. I need to figure out how to reconcile the differences.

**Comment by lj222kj** [comment]
Hey!
Thanks for getting back to me Don! 

Are you aware of any other library that supports all 3 major platforms? (Android, iOS, Windows phone) 

Thanks!

**Comment by don** [comment]
I've heard they have Windows support. Have you tried it? Does it work well?

**Comment by PeacePan** [comment]
hi,

I'm tried randdusing's plugin, but the api design is too complicated for me.

On Windows UWP platform, randdusing's plugin not implement scan and connect(pair) api.

I'm need these feature, because I don't want my users to operate bluetooth settings.

I'm forked this plugin to develop my Windows UWP, maybe you can refer my repository.

It used javascript to write. (depend on WinJS)

https://github.com/PeacePan/cordova-plugin-ble-central/tree/windows-dev/src/windows

It's still in developing

**Comment by dmartinpro** [comment]
Any progress? Maybe W10 is more friendly?

**Comment by VinceFa** [comment]
Hi ! I would like to know if Windows support is still planned, especially for Windows 10.

**Comment by don** [comment]
See #368
