### ISSUE TITLE
ble.write() Writting not permitted

### ISSUE THREAD

**Issue by AlbynoMiya** [don/cordova-plugin-ble-central#224]
Hey, I am trying to communicate with a BluefruitLE using an iOs application. I can scan and connect to it but I can't send any data. The error is Writing not permitted. Any ideas?

**Comment by don** [comment]
The peripheral determines what you can do with the characteristic.

For some older versions of BluefruitLE you need to call `ble.writeWithoutResponse` instead of `ble.write`.

Look at the [JSON description](https://github.com/don/cordova-plugin-ble-central/#peripheral-data) of the peripheral when you connect. It will list the characteristics and permissions.

**Comment by AlbynoMiya** [comment]
Thanks mate. Turns out that my BLE device doesn't support ble.write.
