### ISSUE TITLE
Plugin ID is different on iOS and Android

### ISSUE THREAD

**Issue by alienbrett** [don/cordova-plugin-ble-central#279]
when running the same code on ios and android, the plugin returns two different strings for the Bluetooth device id. ios returns a string that looks like a UUID, while the Android build returns a string that looks like a mac address or an ipv6 address.
Why are these different, and is there any cross-platform device id?

**Comment by don** [comment]
On Android you get the MAC address of the peripheral. 

iOS hides the MAC address and generates a UUID for the device. The UUID for a device should be consistent on your iPhone, but if you scan the same peripheral from another iPhone, the second phone will get a different UUID.  There's nothing  that can do about this, it's Apple's decision for how BLE works. In practice, it's not much of an issue since the id is discovered by scanning.
