### ISSUE TITLE
ble.isConnected slow response

### ISSUE THREAD

**Issue by Gonoshift** [don/cordova-plugin-ble-central#319]
Hello Don, great work on this plugin!
I've ran into an annoying issue, but I don't know if the following behavior is expected or not.
If I connect to a device from Android (lets say and Arduino with a ble module), everything works as expected, but if I reset the device or turn if off, calling ble.isConnected reports a **connected** status for several times before finally reporting the correct **disconnected** status, why is that?

I get an output like:
connected
connected
connected
...
connected
disconnected
disconnected
...

Is it possible to have a faster reply to status change?

EDIT:
It seems that a 20seconds timeout is in place, I'm further investigating...

**Comment by winfinit** [comment]
@Gonoshift were you able to track this down?

**Comment by Gonoshift** [comment]
@winfinit So far it seems that either BLE modules (hw) have this timeout inside, that dictates after how many seconds the connection is considered non responsive/offline. The timeout could be changed in Nordic chips but they have to be reflashed with the new parameter inside. I didn't have the chance to try yet btw...

**Comment by don** [comment]
I don't think there's much you can do about this. 

Rather than repeatedly calling `ble.isConnected` I'd recommend writing for the the plugin to tell you the device disconnected. The failureCallback from `ble.connect` is a long running callback and will be called whenever the peripheral unexpectedly disconnects.

Sometimes this is immediate. Other times there is a delay before Android sees the disconnect.

[ble.connect(device_id, connectSuccess, connectFailure);](https://github.com/don/cordova-plugin-ble-central#connect)

**Comment by Gonoshift** [comment]
Hey @don you mean that the long running callback replies faster (even if still with a delay) than the `ble.isConnected` ?

**Comment by don** [comment]
@Gonoshift some devices still have a delay when they disconnect, but I think you'll get notified faster using the callback.
