### ISSUE TITLE
Missing notification when devices reply fast.

### ISSUE THREAD

**Issue by Rlopez** [don/cordova-plugin-ble-central#321]
I am having this funky issue were I don't get notifications in some cases.
My code looks like this:

```
ble.write(connectedDevice.id, connectedDevice.service, connectedDevice.cSPP, stringToBytes(string + '\r'),
    function(){
        var result = [];
        //console.log("written!");
        var string = "";
        ble.startNotification(connectedDevice.id, connectedDevice.service, connectedDevice.cSPP,
            function(buffer){
                string += bytesToString(buffer);
```

What happens is that, in the cases where the remote device (Arduino+BT) replies very quickly, it is very likely that I won't get the reply. The solution I have at the moment is to add a delay before replying on the Arduino+BT side, so I don't loose any data.

I've also tried to extract the callback and sign up just before the write, just to make sure we don't have to wait for the success callback of `write` same result, though

```
Notifications(callback);
ble.write(connectedDevice.id, connectedDevice.service, connectedDevice.cSPP, stringToBytes(string + '\r'),
    function(){console.log("written!");},
    function(){console.error("couldn't write!");}
```

A possible way around would be to start the writing **inside** the notification (once it is started), but of course the success callback won't be called if the writing is not done (only gets called when data arrives)
The reason I have this write/notify cycles is that I have different callbacks depending on the message that is sent (if I ask for "time" I send the result to a function that takes unixTime ). I am using the library + BT4.0 in a SPP sort of way (by means of the HM-11 module)

Btw, what an awesome library! I was very happy with your BTClassic one, and this one rocks just as much! :D

**Comment by don** [comment]
@Rlopez The solution is to separate the notification and the write. Think of them as two independent operations.

After you connect to the device, start the notification on the characteristic. Now your app is ready to receive data on the callback. It's usually fine to keep this notification in place rather than adding and removing notifications.

Once the notification is in place you can call write and your app should receive the response now matter how quickly the peripheral sends it.
