### ISSUE TITLE
Working with Beacon Devices

### ISSUE THREAD

**Issue by jimboidaho** [don/cordova-plugin-ble-central#387]
I am looking at working with some Beacon devices for my app and I am wondering if plugin is capable of changing settings to the Beacon.  What I will need is the ability to add part of an ID that will be the same for all my customers and also an ID that provides me the info on how to make the app handle reading the Beacon.  Last, each Beacon will need to have a unique ID so I know which customer is providing the Beacon. 

As far as the customer's app that I provide, it will only read that info provided for the customer and react accordingly depending on what my customer wants to do with the Beacon(s).  

You need to understand that I have never worked with bluetooth before but I have looked at your plugin and I have actually made the Beacon provided id info.
Thanks.

**Comment by don** [comment]
Using this plugin, you can get iBeacon data on Android devices but you need to parse it yourself. You can *not* get iBeacon data on iOS because the OS removes beacon data from the advertising info. Try  [cordova-plugin-ibeacon](https://github.com/petermetz/cordova-plugin-ibeacon).

If there is a Bluetooth low energy service for managing beacons, you can use this plugin to write an app that will read and write characteristic to update the configuration.
