### ISSUE TITLE
Issue with read vs startNotification method

### ISSUE THREAD

**Issue by vsavic** [don/cordova-plugin-ble-central#395]
How come that when I attach startNotification success callback method, I manage to get data, but when I use read I don't get anything. I'm using HM-10 BLE.

Also, maybe little bit off-topic, but in case that I must use startNotification success callback method how can I know when reading is done? Is there any equivalent to something like this: 

`while (Serial.available() > 0)
{
//...
}`

I'm asking because, what if you need to get data in chunks, so for example one full message transmission will trigger multiple callback calls.

**Comment by simon4546** [comment]
+1

**Comment by don** [comment]
The peripheral, rather than the app, controls how you access the characteristics. The characteristic has properties that say if you're allowed to read, write or get notifications. Use an app like LightBlue Explorer (on iOS) or nRF Connect on Android to check out the properties. Alternately you can look at the JSON returned when you connect to the peripheral.

If you call `read` it's a one time thing, you get the value of the characteristic.

When you `start notifications`, your callback function gets called every time the characteristic value changes on the peripheral. The callback might never get called or it could get called multiple times per second.

The concept of Serial.available doesn't really make sense with Bluetooth Low Energy. With BLE, characteristics have values that you can access. The confusion is many devices like the HM-10 tries use Bluetooth low energy mimic Bluetooth Classic's Serial Port Profile. It works, it's just a bit of a kludge.

You should be able to adapt the [bluefruit](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle) or [redbear](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/redbearlab) examples to work with the HM-10 by adjusting the service and characteristics.
