### ISSUE TITLE
Device change ID after pairing

### ISSUE THREAD

**Issue by Samb101** [don/cordova-plugin-ble-central#465]
Hello Don,

I've encountered a issue  (which i think is not due to your plugin)

I dialog with an Android device and an Iphone App.
Ionic and your plugin are on the android device.

After few minutes of pairing, the Iphone App has changed his ID. 
So on my android when I try to connect to the already-paired iPhone, it connecting to void because the iPhone has changed his ID.

The only way I've found for now is to remove the pairing; then the iPhone with his new and true ID appears.

If you have any clues or tracks to follow..
Thanks you very much.

PS : this issue is only encoutered with Android  6 + Bluetooth 4.0. It doesn't appear with Android 7 & Bluetooth > 4.1

**Comment by don** [comment]
This sounds like a peripheral issue. Some BLE 4.1+ devices support multiple connections but most do not. Yours probably does since it works with Android 7. Maybe it's a Bluetooth 4.0 vs 4.1 thing?

I'd enable the [Bluetooth HCI snoop log](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app) on both devices, then compare the differences using Wireshark.
