### ISSUE TITLE
Unable to read Tx characteristic value of Noridic UART service value from LinkitOne board as Central

### ISSUE THREAD

**Issue by suvi-ngaige** [don/cordova-plugin-ble-central#495]
Hi
I am using **NRF51** as **Peripheral** ble device and **Linkitone** as **Central** ble device.
From nordic, Using nordic  uart service , sending string to central device after enabling notification.
On linkitone side(Central ble), it successfully get Service UUID, Characteristic UUID but **failed to get value of Characteristic(I am interested in Tx characteristic).** 
Using **LGATTC** example for linkitone, The part of program which should display the value is mentioned below.

In this program

 **if (c.queryNotification(serviceUUID, isPrimary, characteristicUUID, value))
        {
            Serial.printf("[LGATTC ino]notification data[%s][%d]", value.value, value.len);
            Serial.println();
        }**

This function fails.
Why this function fails to invoke.
Is this reason, for unable to get value Or anything else????

**if ((properties & LGATT_CHAR_PROP_READ) == LGATT_CHAR_PROP_READ)**

This function read the value, but it's garbage value. 

Guide me, I need help as soon as possible.

**Comment by don** [comment]
@suvi-ngaige I'm not familiar with the linkitone board. If it uses the Nordic UART service it should work with like the RedBear Lab and Adafruit boards. Checkout the [redbear example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/redbearlab) and [adafruit example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle).

From Cordova rather than reading the TX(0x0002) characteristic, it's better to subscribe for notifications with [ble.startNotification](https://github.com/don/cordova-plugin-ble-central#startnotification) rather then [ble.read](https://github.com/don/cordova-plugin-ble-central#read).
