### ISSUE TITLE
Easy wrapper for isConnected?

### ISSUE THREAD

**Issue by jake-freshinup** [don/cordova-plugin-ble-central#554]
I was trying to make a small Javascript function for isConnect to minimize code duplication but I am having issues:

```
function isBlueToothConnectedToID(bluetooth_id){
var status = false;
ble.isConnected(
      bluetooth_id,
      function() {
          status = true;
      },
      function() {
          status =  false;
      }
    );
return status
}
```

Is there an easy way to wrap some of these function to return true/false rather than running ble.isConencted all of the time?

**Comment by don** [comment]
@jake-freshinup that won't work because the calls to Cordova are asynchronous. 

I find for many apps you don't need isConnected. You can have your app track the connected state. When you call [connect](https://github.com/don/cordova-plugin-ble-central#connect), you know you're connected when the success callback is called. If the device disconnects at any point in the future, the failure callback of connect will be called.
