### ISSUE TITLE
Why dont you merge the DFU features from "fxe-gear/cordova-plugin-ble-central"?

### ISSUE THREAD

**Issue by LabDeve** [don/cordova-plugin-ble-central#639]
Why dont you merge the DFU features from "fxe-gear/cordova-plugin-ble-central"?

**Comment by EarthLord** [comment]
Please do so. It'll be helpful for many of us.

**Comment by don** [comment]
The idea was to keep them separate since that is nRF specific. A better solution might be to move the DFU to a separate plugin that works with this code. @zabojad was working on some plugin hooks which would probably help here.

If someone makes clean pull request I'll probably merge it in. If you're creating a pull request, it would be good to make the Nordic dependencies optional. I like this idea, but I'm not willing to spend time implementing it.

/cc @tomasbedrich

**Comment by tomasbedrich** [comment]
I also like the idea, but I don't work with Cordova anymore, therefore I cannot serve. 🤷‍♂
