### ISSUE TITLE
How to get txPower?

### ISSUE THREAD

**Issue by hamzadiaz** [don/cordova-plugin-ble-central#760]
I managed to display scanned devices and I can see the RSSI of each device, but I can't find the txPower. This parameter has two definitions:

1. The transmitted power of the peripheral.
2. The received power 1 meter away from the peripheral. (RSSI at 1 meter)

Any Ideas how to calculate it?

After going through docummentation I found that the advertising key will contain the txPower:
![scnsht](https://user-images.githubusercontent.com/31761614/81438280-ca045b00-916c-11ea-92a9-ead3a4dde3ac.jpeg)
_Screenshot from Android_

As you can see after I translate the advertising using  `new Uint8Array(device.advertising) `thats the content I get. Is there a way to translate it? for both IOS and Android?

Thanks

**Comment by hamzadiaz** [comment]
Update,

I figure out how to translate Byte to string using the `parseAdvertisingData(buffer)` that you provide and this the advertising information that I get:
![image](https://user-images.githubusercontent.com/31761614/81614461-5cf8fb80-93e0-11ea-9e9f-4ac358dc22a8.png)

**Comment by peitschie** [comment]
Just noting, it's very likely likely those are not actually empty, and are instead being displayed as `{}` due to `parseAdvertisingData` returning typed arrays or array buffers, but the formatter is trying to render this an object with no keys.

I'm closing this out as there's nothing obviously different the plugin can do here. But, feel free to re-open if you are still needing help with this!
