### ISSUE TITLE
Best approach to debug this?

### ISSUE THREAD

**Issue by sandervanhooft** [don/cordova-plugin-ble-central#797]
Hi,

I'm using this plugin (big thanks!) with Capacitor.

When transferring a file with sensor readings from the bluetooth device to the mobile device:

- the file ends up great in the Android app.
- the file is missing a lot of bytes in the iOS app, rendering it unusable.

I'm using the same js code for both builds. What's a good approach for debugging this issue?

**Comment by don** [comment]
BLE isn't really made for transferring files. If you are writing to a characteristic, try making the properties write rather than writeWithoutResponse. I think writeWithoutResponse will drop data. I've successfully read lots of data with notifications from a peripheral to iOS. However if you update too fast, it might not get all data. IIRC you need at least 30ms between updates. HTH
