### ISSUE TITLE
Autoconnect stops working after a day or so (iOS - Ionic 5)

### ISSUE THREAD

**Issue by KyleJJ** [don/cordova-plugin-ble-central#836]
I'm setting up autoConnect for the user's devices when the app is launched using the code below. This works great for about a day and a half, then stops working. According to the [docs](https://github.com/don/cordova-plugin-ble-central#autoconnect) autoConnect is not supposed to timeout and should wait forever for the device to come back in range. I found [this thread](https://github.com/don/cordova-plugin-ble-central/issues/726) from a year ago discussing this issue and concluding that it's due to the way iOS kills inactive apps. I'm wondering if anyone has found a workaround?

`this.ble.scan([], 5).subscribe(device => {});`
`setTimeout(() => {`
`  for (let i = 0; i < this.devices.length; i++) {`
`    this.ble.autoConnect(this.devices[i].id, connected => this.deviceConnected(i), disconnected => {});`
`  }`
`}, 5000);`

I'm including these background modes:
`<string>bluetooth-central</string>`
`<string>location</string>`
`<string>processing</string>`
`<string>fetch</string>`

Any help is greatly appreciated, thank you.

**Comment by KyleJJ** [comment]
I did some more digging and it turns out iOS is killing the app after some time, and although [they do have methods to restore bluetooth from the background](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW5), this plugin does not have them implemented. I'm switching to [randdusing's BLE plugin](https://github.com/randdusing/cordova-plugin-bluetoothle) which appears to have those methods implemented.

**Comment by peitschie** [comment]
As of 1.4.2, this behaviour is hopefully fixed: https://github.com/don/cordova-plugin-ble-central/pull/888

There is now support for iOS state restoration, which allows the connect call to continue to operate as expected.
Note, when iOS relaunches the application due to a background Bluetooth event, the app will need to call `autoConnect` once again to resume the connection loop. Failure to do so within 10s may result in iOS shutting the app back down again.

More discussion on this behaviour can be found at #717
