### ISSUE TITLE
cross platform connection

### ISSUE THREAD

**Issue by Goldtek** [don/cordova-plugin-ble-central#860]
Please how can i use the mac address i got in android though saved to my account and use it to scan and get the uuid for ios to use and connect

**Comment by peitschie** [comment]
Unfortunately, what you are requesting is not trivially possible due to limitations on iOS. To achieve what you're wanting you need the MAC address to be made available in the advertising packet or via another characteristic you can read on connection to the device.

I'll close this out as there's nothing that can be done within the plugin to help here, unfortunately. However, feel free to continue the discussion here if you want.
