### ISSUE TITLE
ionic cordova getting 133 error for ble.write() in Android device

### ISSUE THREAD

**Issue by megha2021** [don/cordova-plugin-ble-central#994]
I am using ionic Cordova, the Ble plugin is working fine for all other methods but when I use the write method it throws 133 error and it is happening only in Android, the same code works in IOS. Please let me know the solution.

**Comment by peitschie** [comment]
Hiya @megha2021 

An error like 133 is a GATT error returned by Android, and unlikely to be something caused by the plugin.

It's worth double-checking that the peripheral supports the type of write you're using (`write` vs `writeWithoutResponse`).

Some things I'd suggest to trying:
1. Check if you get the same problem across multiple types of Android devices
2. See if you get the same result if you try and write using another application such as [nrf Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp)
